# Setup
locale:       "en"
title:        "Based on Jekyll"

# Others
markdown: kramdown

exclude:
        - LICENSE.txt
        - backgroundBuilder.bat
        - pushToRetRemote.bat
        - Gemfile
        - Gemfile.lock