# Setup
locale:       "en"
title:        "Based on Jekyll"
# Others
markdown: kramdown
include:
        - index.md

exclude:
        - README.md
        - LICENSE.txt
        - backgroundBuilder.bat
        - Gemfile
        - Gemfile.lock